Move srand out of weak entropy poll loop
ARMmbed/mbed-client-mbed-tls pull request #61
Opened 2016-12-20 14:47 UTC by kuggenhoffen

2016-12-20 14:50 UTC, kuggenhoffen commented
@simosillankorva @korjaa @anttiylitokola @TeroJaasko

2016-12-21 09:49 UTC, korjaa approved these changes
Looks good to me.

2017-02-15 13:41 UTC, JanneKiiskila requested changes

2017-02-15 13:41 UTC, JanneKiiskila commented on source/m2mconnectionsecuritypimpl.cpp
> +    srand(rdm);
Should this use a PAL random number API instead?

2017-02-15 14:38 UTC, simosillankorva commented on source/m2mconnectionsecuritypimpl.cpp
> +    srand(rdm);
This code will be removed anyway when we merge the PAL TLS version https://github.com/ARMmbed/mbed-client-mbed-tls/pull/63.

2017-04-06 08:29 UTC, yogpan01 commented
Not valid anymore.

2017-04-06 08:29 UTC, closed without merging